# Generated by Django 5.2 on 2025-07-04 00:49

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù]+((?:[\\s][a-zá-ùA-ZÁ-Ù]+)?)+$')])),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='A descrição deve conter apenas letras e números', regex='^[a-zá-ùA-ZÁ-Ù0-9]+((?:[\\s][a-zá-ùA-ZÁ-Ù0-9]+)?)+([.]?)$')])),
                ('status', models.CharField(choices=[('AP', 'A Pagar'), ('P', 'Paga')], max_length=2)),
                ('categories', models.ManyToManyField(related_name='expenses', to='categories.category')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='periods.period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
