# Generated by Django 5.2 on 2025-07-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='categories.category'),
        ),
    ]
