# Generated by Django 5.2 on 2025-06-30 18:03

import django.core.validators
import django.utils.timezone
import users.managers
import users.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='O nome deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù]+((?:[\\s][a-zá-ùA-ZÁ-Ù]+)?)+$')], verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='O email está em format inválido', regex='^[a-zA-Z0-9._]+@[a-z]+\\.com$')], verbose_name='email address')),
                ('cpf', models.CharField(max_length=11, null=True, unique=True, validators=[users.validators.valid_cpf_validator, django.core.validators.RegexValidator(message='O CPF de conter 11 números', regex='^[0-9]{11}$'), django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('date_of_birth', models.DateField(null=True, validators=[users.validators.legal_age_validator], verbose_name='date of birth')),
                ('phone_number', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Número de telefone deve conter apenas números e estar no formato: 'DDD9XXXXXXXX'", regex='^[0-9]{11}$'), django.core.validators.MinLengthValidator(11)], verbose_name='phone number')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='income')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
    ]
