# Generated by Django 5.2 on 2026-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='prioridade',
            field=models.CharField(default='MEDIA', max_length=20),
        ),
    ]
