# Generated by Django 5.2 on 2026-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_bugreport_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='bug_reports/'),
        ),
    ]
