# Generated by Django 5.2 on 2026-06-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_bugreport_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='tipo',
            field=models.CharField(choices=[('PROBLEMA', 'Reportar Problema'), ('MELHORIA', 'Sugerir Melhoria')], default='PROBLEMA', max_length=20),
        ),
    ]
