# Generated by Django 5.2 on 2026-06-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_bugreport_prioridade_bugreport_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitação de Suporte', 'verbose_name_plural': 'Solicitações de Suporte'},
        ),
    ]
