# Generated by Django 5.2 on 2025-06-22 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù]+((?:[\\s][a-zá-ùA-ZÁ-Ù]+)?)+$')]),
        ),
    ]
